package com.cengage.nextbook.panopto.soapservice.sessionmgt;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2 2012-03-28T14:09:51.228+05:30 Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "SessionManagement",
                  wsdlLocation = "http://mindtap.hosted.panopto.com/Panopto/PublicAPI/4.0/SessionManagement.svc?wsdl",
                  targetNamespace = "http://tempuri.org/")
public class SessionManagement extends Service {
    
    public static final URL WSDL_LOCATION;
    
    public static final QName SERVICE = new QName("http://tempuri.org/", "SessionManagement");
    public static final QName BasicHttpBindingISessionManagement = new QName("http://tempuri.org/",
                                                                             "BasicHttpBinding_ISessionManagement");
    static {
        URL url = SessionManagement.class.getResource("http://mindtap.hosted.panopto.com/Panopto/PublicAPI/4.0/SessionManagement.svc?wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(SessionManagement.class.getName())
                                    .log(java.util.logging.Level.INFO, "Can not initialize the default wsdl from {0}",
                                         "http://mindtap.hosted.panopto.com/Panopto/PublicAPI/4.0/SessionManagement.svc?wsdl");
        }
        WSDL_LOCATION = url;
    }
    
    public SessionManagement(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }
    
    public SessionManagement(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }
    
    public SessionManagement() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SessionManagement(WebServiceFeature... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SessionManagement(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICE, features);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SessionManagement(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }
    
    /**
     * 
     * @return returns ISessionManagement
     */
    @WebEndpoint(name = "BasicHttpBinding_ISessionManagement")
    public ISessionManagement getBasicHttpBindingISessionManagement() {
        return super.getPort(BasicHttpBindingISessionManagement, ISessionManagement.class);
    }
    
    /**
     * 
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. Supported features
     * not in the <code>features</code> parameter will have their default values.
     * @return returns ISessionManagement
     */
    @WebEndpoint(name = "BasicHttpBinding_ISessionManagement")
    public ISessionManagement getBasicHttpBindingISessionManagement(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingISessionManagement, ISessionManagement.class, features);
    }
    
}
