package com.cengage.nextbook.panopto.soapservice.usermgt;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.2 2012-04-04T15:43:26.058+05:30 Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "IUserManagement")
@XmlSeeAlso({ObjectFactory.class})
public interface IUserManagement {
    
    @WebResult(name = "CreateExternalGroupResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IUserManagement/CreateExternalGroup",
            output = "http://tempuri.org/IUserManagement/CreateExternalGroupResponse")
    @RequestWrapper(localName = "CreateExternalGroup",
                    targetNamespace = "http://tempuri.org/",
                    className = "com.cengage.nextbook.panopto.soapservice.usermgt.CreateExternalGroup")
    @WebMethod(operationName = "CreateExternalGroup", action = "http://tempuri.org/IUserManagement/CreateExternalGroup")
    @ResponseWrapper(localName = "CreateExternalGroupResponse",
                     targetNamespace = "http://tempuri.org/",
                     className = "com.cengage.nextbook.panopto.soapservice.usermgt.CreateExternalGroupResponse")
    public com.cengage.nextbook.panopto.soapservice.usermgt.Group createExternalGroup(@WebParam(name = "auth",
                                                                                                targetNamespace = "http://tempuri.org/") com.cengage.nextbook.panopto.soapservice.usermgt.AuthenticationInfo auth,
                                                                                      @WebParam(name = "groupName",
                                                                                                targetNamespace = "http://tempuri.org/") java.lang.String groupName,
                                                                                      @WebParam(name = "externalProvider",
                                                                                                targetNamespace = "http://tempuri.org/") java.lang.String externalProvider,
                                                                                      @WebParam(name = "externalId",
                                                                                                targetNamespace = "http://tempuri.org/") java.lang.String externalId,
                                                                                      @WebParam(name = "memberIds",
                                                                                                targetNamespace = "http://tempuri.org/") com.cengage.nextbook.panopto.soapservice.usermgt.ArrayOfguid memberIds);
    
    @Action(input = "http://tempuri.org/IUserManagement/UpdatePassword",
            output = "http://tempuri.org/IUserManagement/UpdatePasswordResponse")
    @RequestWrapper(localName = "UpdatePassword",
                    targetNamespace = "http://tempuri.org/",
                    className = "com.cengage.nextbook.panopto.soapservice.usermgt.UpdatePassword")
    @WebMethod(operationName = "UpdatePassword", action = "http://tempuri.org/IUserManagement/UpdatePassword")
    @ResponseWrapper(localName = "UpdatePasswordResponse",
                     targetNamespace = "http://tempuri.org/",
                     className = "com.cengage.nextbook.panopto.soapservice.usermgt.UpdatePasswordResponse")
    public void updatePassword(@WebParam(name = "auth", targetNamespace = "http://tempuri.org/") com.cengage.nextbook.panopto.soapservice.usermgt.AuthenticationInfo auth,
                               @WebParam(name = "userId", targetNamespace = "http://tempuri.org/") java.lang.String userId,
                               @WebParam(name = "newPassword", targetNamespace = "http://tempuri.org/") java.lang.String newPassword);
    
    @Action(input = "http://tempuri.org/IUserManagement/DeleteUsers",
            output = "http://tempuri.org/IUserManagement/DeleteUsersResponse")
    @RequestWrapper(localName = "DeleteUsers",
                    targetNamespace = "http://tempuri.org/",
                    className = "com.cengage.nextbook.panopto.soapservice.usermgt.DeleteUsers")
    @WebMethod(operationName = "DeleteUsers", action = "http://tempuri.org/IUserManagement/DeleteUsers")
    @ResponseWrapper(localName = "DeleteUsersResponse",
                     targetNamespace = "http://tempuri.org/",
                     className = "com.cengage.nextbook.panopto.soapservice.usermgt.DeleteUsersResponse")
    public void deleteUsers(@WebParam(name = "auth", targetNamespace = "http://tempuri.org/") com.cengage.nextbook.panopto.soapservice.usermgt.AuthenticationInfo auth,
                            @WebParam(name = "userIds", targetNamespace = "http://tempuri.org/") com.cengage.nextbook.panopto.soapservice.usermgt.ArrayOfguid userIds);
    
    @WebResult(name = "CreateInternalGroupResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IUserManagement/CreateInternalGroup",
            output = "http://tempuri.org/IUserManagement/CreateInternalGroupResponse")
    @RequestWrapper(localName = "CreateInternalGroup",
                    targetNamespace = "http://tempuri.org/",
                    className = "com.cengage.nextbook.panopto.soapservice.usermgt.CreateInternalGroup")
    @WebMethod(operationName = "CreateInternalGroup", action = "http://tempuri.org/IUserManagement/CreateInternalGroup")
    @ResponseWrapper(localName = "CreateInternalGroupResponse",
                     targetNamespace = "http://tempuri.org/",
                     className = "com.cengage.nextbook.panopto.soapservice.usermgt.CreateInternalGroupResponse")
    public com.cengage.nextbook.panopto.soapservice.usermgt.Group createInternalGroup(@WebParam(name = "auth",
                                                                                                targetNamespace = "http://tempuri.org/") com.cengage.nextbook.panopto.soapservice.usermgt.AuthenticationInfo auth,
                                                                                      @WebParam(name = "groupName",
                                                                                                targetNamespace = "http://tempuri.org/") java.lang.String groupName,
                                                                                      @WebParam(name = "memberIds",
                                                                                                targetNamespace = "http://tempuri.org/") com.cengage.nextbook.panopto.soapservice.usermgt.ArrayOfguid memberIds);
    
    @WebResult(name = "GetGroupIsPublicResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IUserManagement/GetGroupIsPublic",
            output = "http://tempuri.org/IUserManagement/GetGroupIsPublicResponse")
    @RequestWrapper(localName = "GetGroupIsPublic",
                    targetNamespace = "http://tempuri.org/",
                    className = "com.cengage.nextbook.panopto.soapservice.usermgt.GetGroupIsPublic")
    @WebMethod(operationName = "GetGroupIsPublic", action = "http://tempuri.org/IUserManagement/GetGroupIsPublic")
    @ResponseWrapper(localName = "GetGroupIsPublicResponse",
                     targetNamespace = "http://tempuri.org/",
                     className = "com.cengage.nextbook.panopto.soapservice.usermgt.GetGroupIsPublicResponse")
    public java.lang.Boolean getGroupIsPublic(@WebParam(name = "auth", targetNamespace = "http://tempuri.org/") com.cengage.nextbook.panopto.soapservice.usermgt.AuthenticationInfo auth,
                                              @WebParam(name = "groupId", targetNamespace = "http://tempuri.org/") java.lang.String groupId);
    
    @Action(input = "http://tempuri.org/IUserManagement/SyncExternalUser",
            output = "http://tempuri.org/IUserManagement/SyncExternalUserResponse")
    @RequestWrapper(localName = "SyncExternalUser",
                    targetNamespace = "http://tempuri.org/",
                    className = "com.cengage.nextbook.panopto.soapservice.usermgt.SyncExternalUser")
    @WebMethod(operationName = "SyncExternalUser", action = "http://tempuri.org/IUserManagement/SyncExternalUser")
    @ResponseWrapper(localName = "SyncExternalUserResponse",
                     targetNamespace = "http://tempuri.org/",
                     className = "com.cengage.nextbook.panopto.soapservice.usermgt.SyncExternalUserResponse")
    public void syncExternalUser(@WebParam(name = "auth", targetNamespace = "http://tempuri.org/") com.cengage.nextbook.panopto.soapservice.usermgt.AuthenticationInfo auth,
                                 @WebParam(name = "firstName", targetNamespace = "http://tempuri.org/") java.lang.String firstName,
                                 @WebParam(name = "lastName", targetNamespace = "http://tempuri.org/") java.lang.String lastName,
                                 @WebParam(name = "email", targetNamespace = "http://tempuri.org/") java.lang.String email,
                                 @WebParam(name = "EmailSessionNotifications", targetNamespace = "http://tempuri.org/") java.lang.Boolean emailSessionNotifications,
                                 @WebParam(name = "externalGroupIds", targetNamespace = "http://tempuri.org/") com.cengage.nextbook.panopto.soapservice.usermgt.ArrayOfstring externalGroupIds);
    
    @Action(input = "http://tempuri.org/IUserManagement/SetSystemRole",
            output = "http://tempuri.org/IUserManagement/SetSystemRoleResponse")
    @RequestWrapper(localName = "SetSystemRole",
                    targetNamespace = "http://tempuri.org/",
                    className = "com.cengage.nextbook.panopto.soapservice.usermgt.SetSystemRole")
    @WebMethod(operationName = "SetSystemRole", action = "http://tempuri.org/IUserManagement/SetSystemRole")
    @ResponseWrapper(localName = "SetSystemRoleResponse",
                     targetNamespace = "http://tempuri.org/",
                     className = "com.cengage.nextbook.panopto.soapservice.usermgt.SetSystemRoleResponse")
    public void setSystemRole(@WebParam(name = "auth", targetNamespace = "http://tempuri.org/") com.cengage.nextbook.panopto.soapservice.usermgt.AuthenticationInfo auth,
                              @WebParam(name = "userId", targetNamespace = "http://tempuri.org/") java.lang.String userId,
                              @WebParam(name = "role", targetNamespace = "http://tempuri.org/") com.cengage.nextbook.panopto.soapservice.usermgt.SystemRole role);
    
    @Action(input = "http://tempuri.org/IUserManagement/UnlockAccount",
            output = "http://tempuri.org/IUserManagement/UnlockAccountResponse")
    @RequestWrapper(localName = "UnlockAccount",
                    targetNamespace = "http://tempuri.org/",
                    className = "com.cengage.nextbook.panopto.soapservice.usermgt.UnlockAccount")
    @WebMethod(operationName = "UnlockAccount", action = "http://tempuri.org/IUserManagement/UnlockAccount")
    @ResponseWrapper(localName = "UnlockAccountResponse",
                     targetNamespace = "http://tempuri.org/",
                     className = "com.cengage.nextbook.panopto.soapservice.usermgt.UnlockAccountResponse")
    public void unlockAccount(@WebParam(name = "auth", targetNamespace = "http://tempuri.org/") com.cengage.nextbook.panopto.soapservice.usermgt.AuthenticationInfo auth,
                              @WebParam(name = "userId", targetNamespace = "http://tempuri.org/") java.lang.String userId);
    
    @WebResult(name = "GetUserByKeyResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IUserManagement/GetUserByKey",
            output = "http://tempuri.org/IUserManagement/GetUserByKeyResponse")
    @RequestWrapper(localName = "GetUserByKey",
                    targetNamespace = "http://tempuri.org/",
                    className = "com.cengage.nextbook.panopto.soapservice.usermgt.GetUserByKey")
    @WebMethod(operationName = "GetUserByKey", action = "http://tempuri.org/IUserManagement/GetUserByKey")
    @ResponseWrapper(localName = "GetUserByKeyResponse",
                     targetNamespace = "http://tempuri.org/",
                     className = "com.cengage.nextbook.panopto.soapservice.usermgt.GetUserByKeyResponse")
    public com.cengage.nextbook.panopto.soapservice.usermgt.User getUserByKey(@WebParam(name = "auth",
                                                                                        targetNamespace = "http://tempuri.org/") com.cengage.nextbook.panopto.soapservice.usermgt.AuthenticationInfo auth,
                                                                              @WebParam(name = "userKey",
                                                                                        targetNamespace = "http://tempuri.org/") java.lang.String userKey);
    
    @WebResult(name = "GetGroupResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IUserManagement/GetGroup",
            output = "http://tempuri.org/IUserManagement/GetGroupResponse")
    @RequestWrapper(localName = "GetGroup",
                    targetNamespace = "http://tempuri.org/",
                    className = "com.cengage.nextbook.panopto.soapservice.usermgt.GetGroup")
    @WebMethod(operationName = "GetGroup", action = "http://tempuri.org/IUserManagement/GetGroup")
    @ResponseWrapper(localName = "GetGroupResponse",
                     targetNamespace = "http://tempuri.org/",
                     className = "com.cengage.nextbook.panopto.soapservice.usermgt.GetGroupResponse")
    public com.cengage.nextbook.panopto.soapservice.usermgt.Group getGroup(@WebParam(name = "auth",
                                                                                     targetNamespace = "http://tempuri.org/") com.cengage.nextbook.panopto.soapservice.usermgt.AuthenticationInfo auth,
                                                                           @WebParam(name = "groupId",
                                                                                     targetNamespace = "http://tempuri.org/") java.lang.String groupId);
    
    @Action(input = "http://tempuri.org/IUserManagement/AddMembersToInternalGroup",
            output = "http://tempuri.org/IUserManagement/AddMembersToInternalGroupResponse")
    @RequestWrapper(localName = "AddMembersToInternalGroup",
                    targetNamespace = "http://tempuri.org/",
                    className = "com.cengage.nextbook.panopto.soapservice.usermgt.AddMembersToInternalGroup")
    @WebMethod(operationName = "AddMembersToInternalGroup",
               action = "http://tempuri.org/IUserManagement/AddMembersToInternalGroup")
    @ResponseWrapper(localName = "AddMembersToInternalGroupResponse",
                     targetNamespace = "http://tempuri.org/",
                     className = "com.cengage.nextbook.panopto.soapservice.usermgt.AddMembersToInternalGroupResponse")
    public void addMembersToInternalGroup(@WebParam(name = "auth", targetNamespace = "http://tempuri.org/") com.cengage.nextbook.panopto.soapservice.usermgt.AuthenticationInfo auth,
                                          @WebParam(name = "groupId", targetNamespace = "http://tempuri.org/") java.lang.String groupId,
                                          @WebParam(name = "memberIds", targetNamespace = "http://tempuri.org/") com.cengage.nextbook.panopto.soapservice.usermgt.ArrayOfguid memberIds);
    
    @WebResult(name = "CreateUserResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IUserManagement/CreateUser",
            output = "http://tempuri.org/IUserManagement/CreateUserResponse")
    @RequestWrapper(localName = "CreateUser",
                    targetNamespace = "http://tempuri.org/",
                    className = "com.cengage.nextbook.panopto.soapservice.usermgt.CreateUser")
    @WebMethod(operationName = "CreateUser", action = "http://tempuri.org/IUserManagement/CreateUser")
    @ResponseWrapper(localName = "CreateUserResponse",
                     targetNamespace = "http://tempuri.org/",
                     className = "com.cengage.nextbook.panopto.soapservice.usermgt.CreateUserResponse")
    public java.lang.String createUser(@WebParam(name = "auth", targetNamespace = "http://tempuri.org/") com.cengage.nextbook.panopto.soapservice.usermgt.AuthenticationInfo auth,
                                       @WebParam(name = "user", targetNamespace = "http://tempuri.org/") com.cengage.nextbook.panopto.soapservice.usermgt.User user,
                                       @WebParam(name = "initialPassword", targetNamespace = "http://tempuri.org/") java.lang.String initialPassword);
    
    @Action(input = "http://tempuri.org/IUserManagement/UpdateUserBio",
            output = "http://tempuri.org/IUserManagement/UpdateUserBioResponse")
    @RequestWrapper(localName = "UpdateUserBio",
                    targetNamespace = "http://tempuri.org/",
                    className = "com.cengage.nextbook.panopto.soapservice.usermgt.UpdateUserBio")
    @WebMethod(operationName = "UpdateUserBio", action = "http://tempuri.org/IUserManagement/UpdateUserBio")
    @ResponseWrapper(localName = "UpdateUserBioResponse",
                     targetNamespace = "http://tempuri.org/",
                     className = "com.cengage.nextbook.panopto.soapservice.usermgt.UpdateUserBioResponse")
    public void updateUserBio(@WebParam(name = "auth", targetNamespace = "http://tempuri.org/") com.cengage.nextbook.panopto.soapservice.usermgt.AuthenticationInfo auth,
                              @WebParam(name = "userId", targetNamespace = "http://tempuri.org/") java.lang.String userId,
                              @WebParam(name = "bio", targetNamespace = "http://tempuri.org/") java.lang.String bio);
    
    @Action(input = "http://tempuri.org/IUserManagement/DeleteGroup",
            output = "http://tempuri.org/IUserManagement/DeleteGroupResponse")
    @RequestWrapper(localName = "DeleteGroup",
                    targetNamespace = "http://tempuri.org/",
                    className = "com.cengage.nextbook.panopto.soapservice.usermgt.DeleteGroup")
    @WebMethod(operationName = "DeleteGroup", action = "http://tempuri.org/IUserManagement/DeleteGroup")
    @ResponseWrapper(localName = "DeleteGroupResponse",
                     targetNamespace = "http://tempuri.org/",
                     className = "com.cengage.nextbook.panopto.soapservice.usermgt.DeleteGroupResponse")
    public void deleteGroup(@WebParam(name = "auth", targetNamespace = "http://tempuri.org/") com.cengage.nextbook.panopto.soapservice.usermgt.AuthenticationInfo auth,
                            @WebParam(name = "groupId", targetNamespace = "http://tempuri.org/") java.lang.String groupId);
    
    @WebResult(name = "ListUsersResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IUserManagement/ListUsers",
            output = "http://tempuri.org/IUserManagement/ListUsersResponse")
    @RequestWrapper(localName = "ListUsers",
                    targetNamespace = "http://tempuri.org/",
                    className = "com.cengage.nextbook.panopto.soapservice.usermgt.ListUsers")
    @WebMethod(operationName = "ListUsers", action = "http://tempuri.org/IUserManagement/ListUsers")
    @ResponseWrapper(localName = "ListUsersResponse",
                     targetNamespace = "http://tempuri.org/",
                     className = "com.cengage.nextbook.panopto.soapservice.usermgt.ListUsersResponse2")
    public com.cengage.nextbook.panopto.soapservice.usermgt.ListUsersResponse listUsers(@WebParam(name = "auth",
                                                                                                  targetNamespace = "http://tempuri.org/") com.cengage.nextbook.panopto.soapservice.usermgt.AuthenticationInfo auth,
                                                                                        @WebParam(name = "parameters",
                                                                                                  targetNamespace = "http://tempuri.org/") com.cengage.nextbook.panopto.soapservice.usermgt.ListUsersRequest parameters,
                                                                                        @WebParam(name = "searchQuery",
                                                                                                  targetNamespace = "http://tempuri.org/") java.lang.String searchQuery);
    
    @Action(input = "http://tempuri.org/IUserManagement/RemoveMembersFromInternalGroup",
            output = "http://tempuri.org/IUserManagement/RemoveMembersFromInternalGroupResponse")
    @RequestWrapper(localName = "RemoveMembersFromInternalGroup",
                    targetNamespace = "http://tempuri.org/",
                    className = "com.cengage.nextbook.panopto.soapservice.usermgt.RemoveMembersFromInternalGroup")
    @WebMethod(operationName = "RemoveMembersFromInternalGroup",
               action = "http://tempuri.org/IUserManagement/RemoveMembersFromInternalGroup")
    @ResponseWrapper(localName = "RemoveMembersFromInternalGroupResponse",
                     targetNamespace = "http://tempuri.org/",
                     className = "com.cengage.nextbook.panopto.soapservice.usermgt.RemoveMembersFromInternalGroupResponse")
    public void removeMembersFromInternalGroup(@WebParam(name = "auth", targetNamespace = "http://tempuri.org/") com.cengage.nextbook.panopto.soapservice.usermgt.AuthenticationInfo auth,
                                               @WebParam(name = "groupId", targetNamespace = "http://tempuri.org/") java.lang.String groupId,
                                               @WebParam(name = "memberIds", targetNamespace = "http://tempuri.org/") com.cengage.nextbook.panopto.soapservice.usermgt.ArrayOfguid memberIds);
    
    @Action(input = "http://tempuri.org/IUserManagement/SetGroupIsPublic",
            output = "http://tempuri.org/IUserManagement/SetGroupIsPublicResponse")
    @RequestWrapper(localName = "SetGroupIsPublic",
                    targetNamespace = "http://tempuri.org/",
                    className = "com.cengage.nextbook.panopto.soapservice.usermgt.SetGroupIsPublic")
    @WebMethod(operationName = "SetGroupIsPublic", action = "http://tempuri.org/IUserManagement/SetGroupIsPublic")
    @ResponseWrapper(localName = "SetGroupIsPublicResponse",
                     targetNamespace = "http://tempuri.org/",
                     className = "com.cengage.nextbook.panopto.soapservice.usermgt.SetGroupIsPublicResponse")
    public void setGroupIsPublic(@WebParam(name = "auth", targetNamespace = "http://tempuri.org/") com.cengage.nextbook.panopto.soapservice.usermgt.AuthenticationInfo auth,
                                 @WebParam(name = "groupId", targetNamespace = "http://tempuri.org/") java.lang.String groupId,
                                 @WebParam(name = "isPublic", targetNamespace = "http://tempuri.org/") java.lang.Boolean isPublic);
    
    @Action(input = "http://tempuri.org/IUserManagement/UpdateContactInfo",
            output = "http://tempuri.org/IUserManagement/UpdateContactInfoResponse")
    @RequestWrapper(localName = "UpdateContactInfo",
                    targetNamespace = "http://tempuri.org/",
                    className = "com.cengage.nextbook.panopto.soapservice.usermgt.UpdateContactInfo")
    @WebMethod(operationName = "UpdateContactInfo", action = "http://tempuri.org/IUserManagement/UpdateContactInfo")
    @ResponseWrapper(localName = "UpdateContactInfoResponse",
                     targetNamespace = "http://tempuri.org/",
                     className = "com.cengage.nextbook.panopto.soapservice.usermgt.UpdateContactInfoResponse")
    public void updateContactInfo(@WebParam(name = "auth", targetNamespace = "http://tempuri.org/") com.cengage.nextbook.panopto.soapservice.usermgt.AuthenticationInfo auth,
                                  @WebParam(name = "userId", targetNamespace = "http://tempuri.org/") java.lang.String userId,
                                  @WebParam(name = "firstName", targetNamespace = "http://tempuri.org/") java.lang.String firstName,
                                  @WebParam(name = "lastName", targetNamespace = "http://tempuri.org/") java.lang.String lastName,
                                  @WebParam(name = "email", targetNamespace = "http://tempuri.org/") java.lang.String email,
                                  @WebParam(name = "sendNotifications", targetNamespace = "http://tempuri.org/") java.lang.Boolean sendNotifications);
    
    @WebResult(name = "GetUsersResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IUserManagement/GetUsers",
            output = "http://tempuri.org/IUserManagement/GetUsersResponse")
    @RequestWrapper(localName = "GetUsers",
                    targetNamespace = "http://tempuri.org/",
                    className = "com.cengage.nextbook.panopto.soapservice.usermgt.GetUsers")
    @WebMethod(operationName = "GetUsers", action = "http://tempuri.org/IUserManagement/GetUsers")
    @ResponseWrapper(localName = "GetUsersResponse",
                     targetNamespace = "http://tempuri.org/",
                     className = "com.cengage.nextbook.panopto.soapservice.usermgt.GetUsersResponse")
    public com.cengage.nextbook.panopto.soapservice.usermgt.ArrayOfUser getUsers(@WebParam(name = "auth",
                                                                                           targetNamespace = "http://tempuri.org/") com.cengage.nextbook.panopto.soapservice.usermgt.AuthenticationInfo auth,
                                                                                 @WebParam(name = "userIds",
                                                                                           targetNamespace = "http://tempuri.org/") com.cengage.nextbook.panopto.soapservice.usermgt.ArrayOfguid userIds);
    
    @Action(input = "http://tempuri.org/IUserManagement/ResetPassword",
            output = "http://tempuri.org/IUserManagement/ResetPasswordResponse")
    @RequestWrapper(localName = "ResetPassword",
                    targetNamespace = "http://tempuri.org/",
                    className = "com.cengage.nextbook.panopto.soapservice.usermgt.ResetPassword")
    @WebMethod(operationName = "ResetPassword", action = "http://tempuri.org/IUserManagement/ResetPassword")
    @ResponseWrapper(localName = "ResetPasswordResponse",
                     targetNamespace = "http://tempuri.org/",
                     className = "com.cengage.nextbook.panopto.soapservice.usermgt.ResetPasswordResponse")
    public void resetPassword(@WebParam(name = "auth", targetNamespace = "http://tempuri.org/") com.cengage.nextbook.panopto.soapservice.usermgt.AuthenticationInfo auth,
                              @WebParam(name = "userId", targetNamespace = "http://tempuri.org/") java.lang.String userId);
    
    @WebResult(name = "CreateUsersResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IUserManagement/CreateUsers",
            output = "http://tempuri.org/IUserManagement/CreateUsersResponse")
    @RequestWrapper(localName = "CreateUsers",
                    targetNamespace = "http://tempuri.org/",
                    className = "com.cengage.nextbook.panopto.soapservice.usermgt.CreateUsers")
    @WebMethod(operationName = "CreateUsers", action = "http://tempuri.org/IUserManagement/CreateUsers")
    @ResponseWrapper(localName = "CreateUsersResponse",
                     targetNamespace = "http://tempuri.org/",
                     className = "com.cengage.nextbook.panopto.soapservice.usermgt.CreateUsersResponse")
    public com.cengage.nextbook.panopto.soapservice.usermgt.ArrayOfUser createUsers(@WebParam(name = "auth",
                                                                                              targetNamespace = "http://tempuri.org/") com.cengage.nextbook.panopto.soapservice.usermgt.AuthenticationInfo auth,
                                                                                    @WebParam(name = "users",
                                                                                              targetNamespace = "http://tempuri.org/") com.cengage.nextbook.panopto.soapservice.usermgt.ArrayOfUser users);
    
    @WebResult(name = "ListGroupsResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IUserManagement/ListGroups",
            output = "http://tempuri.org/IUserManagement/ListGroupsResponse")
    @RequestWrapper(localName = "ListGroups",
                    targetNamespace = "http://tempuri.org/",
                    className = "com.cengage.nextbook.panopto.soapservice.usermgt.ListGroups")
    @WebMethod(operationName = "ListGroups", action = "http://tempuri.org/IUserManagement/ListGroups")
    @ResponseWrapper(localName = "ListGroupsResponse",
                     targetNamespace = "http://tempuri.org/",
                     className = "com.cengage.nextbook.panopto.soapservice.usermgt.ListGroupsResponse2")
    public com.cengage.nextbook.panopto.soapservice.usermgt.ListGroupsResponse listGroups(@WebParam(name = "auth",
                                                                                                    targetNamespace = "http://tempuri.org/") com.cengage.nextbook.panopto.soapservice.usermgt.AuthenticationInfo auth,
                                                                                          @WebParam(name = "pagination",
                                                                                                    targetNamespace = "http://tempuri.org/") com.cengage.nextbook.panopto.soapservice.usermgt.Pagination pagination);
}
