package com.cengage.nextbook.panopto.soapservice.usermgt;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2 2012-04-04T15:43:26.103+05:30 Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "UserManagement",
                  wsdlLocation = "http://mindtap.hosted.panopto.com/Panopto/PublicAPI/4.0/UserManagement.svc?wsdl",
                  targetNamespace = "http://tempuri.org/")
public class UserManagement extends Service {
    
    public static final URL WSDL_LOCATION;
    
    public static final QName SERVICE = new QName("http://tempuri.org/", "UserManagement");
    public static final QName BasicHttpBindingIUserManagement = new QName("http://tempuri.org/",
                                                                          "BasicHttpBinding_IUserManagement");
    static {
        URL url = UserManagement.class.getResource("http://mindtap.hosted.panopto.com/Panopto/PublicAPI/4.0/UserManagement.svc?wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(UserManagement.class.getName())
                                    .log(java.util.logging.Level.INFO, "Can not initialize the default wsdl from {0}",
                                         "http://mindtap.hosted.panopto.com/Panopto/PublicAPI/4.0/UserManagement.svc?wsdl");
        }
        WSDL_LOCATION = url;
    }
    
    public UserManagement(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }
    
    public UserManagement(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }
    
    public UserManagement() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UserManagement(WebServiceFeature... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UserManagement(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICE, features);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UserManagement(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }
    
    /**
     * 
     * @return returns IUserManagement
     */
    @WebEndpoint(name = "BasicHttpBinding_IUserManagement")
    public IUserManagement getBasicHttpBindingIUserManagement() {
        return super.getPort(BasicHttpBindingIUserManagement, IUserManagement.class);
    }
    
    /**
     * 
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. Supported features
     * not in the <code>features</code> parameter will have their default values.
     * @return returns IUserManagement
     */
    @WebEndpoint(name = "BasicHttpBinding_IUserManagement")
    public IUserManagement getBasicHttpBindingIUserManagement(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingIUserManagement, IUserManagement.class, features);
    }
    
}
